# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sudoku.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sudoku.proto',
  package='ousystems',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0csudoku.proto\x12\tousystems\"!\n\tPublicKey\x12\t\n\x01n\x18\x01 \x01(\x05\x12\t\n\x01\x65\x18\x02 \x01(\x05\"X\n\tsubMatrix\x12\x0f\n\x07subrow0\x18\x01 \x03(\x05\x12\x0f\n\x07subrow1\x18\x02 \x03(\x05\x12\x0f\n\x07subrow2\x18\x03 \x03(\x05\x12\x0b\n\x03src\x18\x04 \x01(\t\x12\x0b\n\x03\x64st\x18\x05 \x01(\t\"=\n\x10\x45ncryptedMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\x0b\n\x03src\x18\x02 \x01(\t\x12\x0b\n\x03\x64st\x18\x03 \x01(\t\"2\n\x06MsgAck\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0b\n\x03src\x18\x02 \x01(\t\x12\x0b\n\x03\x64st\x18\x03 \x01(\t\"\x19\n\x07NullMsg\x12\x0e\n\x06status\x18\x01 \x01(\x05\"\x1b\n\x07\x41\x64\x64ress\x12\x10\n\x08position\x18\x01 \x01(\t\"\x19\n\x05Token\x12\x10\n\x08timeslot\x18\x01 \x01(\x05\x32\x91\x02\n\x0fSecureMessaging\x12:\n\x0cGetPublicKey\x12\x12.ousystems.NullMsg\x1a\x14.ousystems.PublicKey\"\x00\x12H\n\x14SendEncryptedMessage\x12\x1b.ousystems.EncryptedMessage\x1a\x11.ousystems.MsgAck\"\x00\x12:\n\x0cGetSubMatrix\x12\x12.ousystems.Address\x1a\x14.ousystems.subMatrix\"\x00\x12<\n\x12GetRoundRobinToken\x12\x12.ousystems.Address\x1a\x10.ousystems.Token\"\x00\x62\x06proto3'
)




_PUBLICKEY = _descriptor.Descriptor(
  name='PublicKey',
  full_name='ousystems.PublicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='n', full_name='ousystems.PublicKey.n', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='e', full_name='ousystems.PublicKey.e', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=60,
)


_SUBMATRIX = _descriptor.Descriptor(
  name='subMatrix',
  full_name='ousystems.subMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='subrow0', full_name='ousystems.subMatrix.subrow0', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subrow1', full_name='ousystems.subMatrix.subrow1', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='subrow2', full_name='ousystems.subMatrix.subrow2', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src', full_name='ousystems.subMatrix.src', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst', full_name='ousystems.subMatrix.dst', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=150,
)


_ENCRYPTEDMESSAGE = _descriptor.Descriptor(
  name='EncryptedMessage',
  full_name='ousystems.EncryptedMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='ousystems.EncryptedMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src', full_name='ousystems.EncryptedMessage.src', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst', full_name='ousystems.EncryptedMessage.dst', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=213,
)


_MSGACK = _descriptor.Descriptor(
  name='MsgAck',
  full_name='ousystems.MsgAck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ousystems.MsgAck.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='src', full_name='ousystems.MsgAck.src', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dst', full_name='ousystems.MsgAck.dst', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=265,
)


_NULLMSG = _descriptor.Descriptor(
  name='NullMsg',
  full_name='ousystems.NullMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='ousystems.NullMsg.status', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=267,
  serialized_end=292,
)


_ADDRESS = _descriptor.Descriptor(
  name='Address',
  full_name='ousystems.Address',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='ousystems.Address.position', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=294,
  serialized_end=321,
)


_TOKEN = _descriptor.Descriptor(
  name='Token',
  full_name='ousystems.Token',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='timeslot', full_name='ousystems.Token.timeslot', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=348,
)

DESCRIPTOR.message_types_by_name['PublicKey'] = _PUBLICKEY
DESCRIPTOR.message_types_by_name['subMatrix'] = _SUBMATRIX
DESCRIPTOR.message_types_by_name['EncryptedMessage'] = _ENCRYPTEDMESSAGE
DESCRIPTOR.message_types_by_name['MsgAck'] = _MSGACK
DESCRIPTOR.message_types_by_name['NullMsg'] = _NULLMSG
DESCRIPTOR.message_types_by_name['Address'] = _ADDRESS
DESCRIPTOR.message_types_by_name['Token'] = _TOKEN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PublicKey = _reflection.GeneratedProtocolMessageType('PublicKey', (_message.Message,), {
  'DESCRIPTOR' : _PUBLICKEY,
  '__module__' : 'sudoku_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.PublicKey)
  })
_sym_db.RegisterMessage(PublicKey)

subMatrix = _reflection.GeneratedProtocolMessageType('subMatrix', (_message.Message,), {
  'DESCRIPTOR' : _SUBMATRIX,
  '__module__' : 'sudoku_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.subMatrix)
  })
_sym_db.RegisterMessage(subMatrix)

EncryptedMessage = _reflection.GeneratedProtocolMessageType('EncryptedMessage', (_message.Message,), {
  'DESCRIPTOR' : _ENCRYPTEDMESSAGE,
  '__module__' : 'sudoku_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.EncryptedMessage)
  })
_sym_db.RegisterMessage(EncryptedMessage)

MsgAck = _reflection.GeneratedProtocolMessageType('MsgAck', (_message.Message,), {
  'DESCRIPTOR' : _MSGACK,
  '__module__' : 'sudoku_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.MsgAck)
  })
_sym_db.RegisterMessage(MsgAck)

NullMsg = _reflection.GeneratedProtocolMessageType('NullMsg', (_message.Message,), {
  'DESCRIPTOR' : _NULLMSG,
  '__module__' : 'sudoku_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.NullMsg)
  })
_sym_db.RegisterMessage(NullMsg)

Address = _reflection.GeneratedProtocolMessageType('Address', (_message.Message,), {
  'DESCRIPTOR' : _ADDRESS,
  '__module__' : 'sudoku_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.Address)
  })
_sym_db.RegisterMessage(Address)

Token = _reflection.GeneratedProtocolMessageType('Token', (_message.Message,), {
  'DESCRIPTOR' : _TOKEN,
  '__module__' : 'sudoku_pb2'
  # @@protoc_insertion_point(class_scope:ousystems.Token)
  })
_sym_db.RegisterMessage(Token)



_SECUREMESSAGING = _descriptor.ServiceDescriptor(
  name='SecureMessaging',
  full_name='ousystems.SecureMessaging',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=351,
  serialized_end=624,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetPublicKey',
    full_name='ousystems.SecureMessaging.GetPublicKey',
    index=0,
    containing_service=None,
    input_type=_NULLMSG,
    output_type=_PUBLICKEY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SendEncryptedMessage',
    full_name='ousystems.SecureMessaging.SendEncryptedMessage',
    index=1,
    containing_service=None,
    input_type=_ENCRYPTEDMESSAGE,
    output_type=_MSGACK,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetSubMatrix',
    full_name='ousystems.SecureMessaging.GetSubMatrix',
    index=2,
    containing_service=None,
    input_type=_ADDRESS,
    output_type=_SUBMATRIX,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetRoundRobinToken',
    full_name='ousystems.SecureMessaging.GetRoundRobinToken',
    index=3,
    containing_service=None,
    input_type=_ADDRESS,
    output_type=_TOKEN,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SECUREMESSAGING)

DESCRIPTOR.services_by_name['SecureMessaging'] = _SECUREMESSAGING

# @@protoc_insertion_point(module_scope)
